repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: flake8
- repo: git://github.com/pre-commit/mirrors-eslint
  rev: v5.16.0
  hooks:
  -   id: eslint
      additional_dependencies:
      - eslint-config-airbnb-base@13.2.0
      - eslint-plugin-import@2.18.0
      - eslint@5.16.0
